all:
	g++ -std=c++11 frontend.cpp transactions/addCredit.cpp transactions/buy.cpp transactions/create.cpp  transactions/deleteAccount.cpp transactions/login.cpp transactions/logout.cpp transactions/refund.cpp transactions/sell.cpp helper/event.cpp helper/user.cpp helper/fileIO.cpp -o frontend
clean:
	rm frontend